### ISSUE TITLE
QLik API Integration

### ISSUE THREAD

**Issue by llui85** [jxeeno/aust-govt-covid19-stats#1]
It turns out that that the QLik Sense (the product which powers the graphs on the page) [has a remarkably well-documented API](https://help.qlik.com/en-US/sense-developer/May2021/Subsystems/EngineAPI/Content/Sense_EngineAPI/introducing-engine-API.htm) which provides data a lot more accurately than the current scraping process using Puppeteer.

### Advantages of this approach
- Decimals will no longer be rounded. For example, the positive test percentage for Australia yesterday was `0.0014373561076329474`, but the scraped data is rounded to `0.1`
- Scraping is much faster now - [my implementation takes ~12 seconds](https://github.com/llui85/covid19stats-govau/runs/3005226945?check_suite_focus=true) compared to the current ~1 minute.
- The API provides a modification datetime as ISO8601, so the regex that looks for a date in the footnote can be now avoided:

https://github.com/jxeeno/aust-govt-covid19-stats/blob/26790ca22d8cc206dfd73622bd745bc5b235f6bf/scrape.js#L14-L25

Unfortunately we still need to hardcode the ID of each graph as graph titles aren't included for some reason, but these don't change often, and will still be stored in the raw data.

I'm happy to open a PR for this sometime in the next week if you'd like me to. You can see my [basic implementation here](https://github.com/llui85/covid19stats-govau/blob/master/index.js).

**Comment by jxeeno** [comment]
Ooooh, thanks @llui85!

This is great - I'll see if I have a chance to play around with the API over the next week.  Thanks for providing an example implementation :)

**Comment by llui85** [comment]
> Ooooh, thanks @llui85!
> 
> This is great - I'll see if I have a chance to play around with the API over the next week. Thanks for providing an example implementation :)

I've opened a PR ( #2 ), what are your thoughts?
